# This file defines the config for "ct" (chart tester) used by the helm linting GitHub workflow

# Here we define every possible upstream repo our charts use in `requirements.yaml`
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami

lint-conf: .ci/lint-config.yaml