name: Lint and Test Charts

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'charts/**/README.md'
      - 'CODE_OF_CONDUCT.md'
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:

env:
  KUBE_SCORE_VERSION: 1.12.0

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.11.1

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Install Chart dependencies
        run: |
          cd charts/nextcloud && helm dependency build

      - name: Set up kube-score
        run: |
          mkdir /tmp/bin
          wget https://github.com/zegl/kube-score/releases/download/v${{ env.KUBE_SCORE_VERSION }}/kube-score_${{ env.KUBE_SCORE_VERSION }}_linux_amd64 -O /tmp/bin/kube-score
          chmod 755 /tmp/bin/kube-score

      - name: Kube-score generated manifests
        env:
          KUBE_SCORE: /tmp/bin/kube-score
        run: .ci/scripts/kube-score.sh

  chart-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Choose from https://hub.docker.com/r/kindest/node/tags
        KubeVersion: [1.25.8,1.26.3,1.27.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.11.1

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      # python is a requirement for the chart-testing action below (supports yamllint among other tests)
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --config .ci/ct-config.yaml

      - name: Create ${{matrix.KubeVersion}} kind cluster
        uses: helm/kind-action@v1.5.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          node_image: kindest/node:v${{matrix.KubeVersion}}
          cluster_name: kubernetes-${{matrix.KubeVersion}}

      - name: Run chart-testing (install) against ${{matrix.KubeVersion}}
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }} --config .ci/ct-config.yaml
